name: dh-issue-listener
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "30 */5 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ github.workflow }}
    env:
      OAESFILE: ${{ secrets.OAESFILE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Bạn có thể thay đổi phiên bản Node.js nếu cần

      - name: Call reusable Git ls-tree
        if: always()
        uses: ./.github/workflows/common-git-ls-tree.yml@main
      - name: Call reusable Git ls-tree
        if: always()
        uses: dh-hos-code/dh-issue-listener/.github/workflows/common-git-ls-tree.yml@main

      - name: Decrypt oAESFile
        shell: pwsh
        run: |
          if (Test-Path "./oAESFile.js") {
            node ./oAESFile.js --de $env:OAESFILE ./;
            git log -1;
          }
      - name: Git ls-tree
        if: always()
        shell: pwsh
        run: ./.github/scripts-yml/git-ls-tree.ps1

      - name: Execute msbuild@v2 by NodeJS
        shell: bash
        run: |
          node ./dist-dh-issues-o-dh-008.js

      - name: Git ls-tree
        if: always()
        shell: pwsh
        run: ./.github/scripts-yml/git-ls-tree.ps1

      - name: Upload build artifacts v4
        if: always() # Luôn luôn chạy step này, dù các step trước có lỗi
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.workflow }}-artifacts-${{ github.run_id }}
          path: |
            logs
          retention-days: 10 # Định nghĩa thời gian tồn tại (ở đây là 30 ngày)
          compression-level: 9 # maximum compression
