name: dh-issue-listener
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "30 */5 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ github.workflow }}
    env:
      OAESFILE: ${{ secrets.OAESFILE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Bạn có thể thay đổi phiên bản Node.js nếu cần

      - name: Git ls-tree
        if: always()
        shell: pwsh
        run: ./.github/scripts-yml/git-ls-tree.ps1

      - name: Decrypt oAESFile
        shell: pwsh
        run: |
          if (Test-Path "./oAESFile.js") {
            node ./oAESFile.js --de $env:OAESFILE ./;
            git log -1;
          }

      - name: Git ls-tree
        if: always()
        shell: pwsh
        run: ./.github/scripts-yml/git-ls-tree.ps1

      - name: Execute ./dist-dh-issues-o-dh-008.js by NodeJS
        shell: bash
        run: |
          node ./dist-dh-issues-o-dh-008.js

      - name: Save GitHub and other contexts to files
        if: always()
        shell: pwsh
        run: |
          # Tạo thư mục logs nếu chưa tồn tại
          if (-not (Test-Path -Path './contexts')) { New-Item -ItemType Directory -Path './contexts' }

          # Hàm ghi context với try-catch để xử lý lỗi
          function Save-Context {
              param (
                  [string]$contextName,
                  [string]$contextData
              )
              try {
                  $contextData | Out-File -FilePath "./contexts/$contextName-context.json" -Encoding utf8
                  Write-Host "$contextName context saved successfully."
              } catch {
                  Write-Host "Failed to save $contextName context."
              }
          }

          # Ghi các context với try-catch
          Save-Context "github" '${{ toJson(github) }}'
          Save-Context "env" '${{ toJson(env) }}'
          Save-Context "vars" '${{ toJson(vars) }}'
          # Save-Context "job" '${{ toJson(job) }}'
          # Save-Context "jobs" '${{ toJson(jobs) }}'
          # Save-Context "steps" '${{ toJson(steps) }}'
          Save-Context "runner" '${{ toJson(runner) }}'
          Save-Context "secrets" '${{ toJson(secrets) }}'
          Save-Context "strategy" '${{ toJson(strategy) }}'
          Save-Context "matrix" '${{ toJson(matrix) }}'
          Save-Context "needs" '${{ toJson(needs) }}'
          Save-Context "inputs" '${{ toJson(inputs) }}'

      - name: Git ls-tree
        if: always()
        shell: pwsh
        run: ./.github/scripts-yml/git-ls-tree.ps1

      - name: Upload build artifacts v4
        if: always() # Luôn luôn chạy step này, dù các step trước có lỗi
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.workflow }}-artifacts-${{ github.run_id }}
          path: |
            logs
            contexts
          retention-days: 10 # Định nghĩa thời gian tồn tại (ở đây là 30 ngày)
          compression-level: 9 # maximum compression
